name: CI
on:
  push:
    branches:
      - ci
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Fetch libproj
        uses: ./.github/actions/libproj
      - name: Check result
        run: ls -la
