name: CI
on:
  push:
    branches:
      - ci
env:
  PROJ_VERSION: 6.3.1
  PROJ_DATUM: 1.8
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          curl https://download.osgeo.org/proj/proj-${PROJ_VERSION}.tar.gz | tar -xz
          curl -o datum.zip https://download.osgeo.org/proj/proj-datumgrid-${PROJ_DATUM}.zip
          unzip datum.zip -d proj-${PROJ_VERSION}/data
          rm -f datum.zip
      - name: build
        run: |
          cd proj-${PROJ_VERSION}
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ls -la /usr/lib/
          ls -la /usr/lib/x86_64-linux-gnu/
