name: CI
on:
  push:
    branches:
      - ci
env:
  GO111MODULE: on
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src

      - name: Cache libproj
        id: cache-libproj
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/libproj
          key: ${{ runner.os }}-cache-libproj-6_3_1 # 6.3.1 stands for libproj version
          restore-keys: |
            ${{ runner.os }}-cache-libproj-

      - name: Fetch libproj
        if: steps.cache-libproj.outputs.cache-hit != 'true'
        uses: ./.github/actions/libproj

      - name: Install libproj
        run: |
          sudo cp $GITHUB_WORKSPACE/libproj/* /usr/lib

      - name: setup env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13.8"

      - name: Cache go modules
        uses: actions/cache@v1
        id: cache-go
        with:
          path: ${{ github.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-cache-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-cache-go-

      - name: Download go modules
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          cd src 
          make download

      - name: Test
        run: |
          cd src
          make lint
          make test
          make typescript
