name: CI
on:
  push:
    branches:
      - ci
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Fetch libproj
        uses: ./.github/actions/libproj
      - name: Install lib
        run: |
          echo "$GITHUB_WORKSPACE"
          echo "$HOME"
          ls -la $GITHUB_WORKSPACE
          ls -la $HOME
          sudo mkdir -p /usr/lib/x86_64-linux-gnu/
          sudo cp $HOME/libproj/* /usr/lib/x86_64-linux-gnu/
          rm -rf $HOME/libproj
          ls -la /usr/lib/x86_64-linux-gnu/ | grep proj
