name: CI
on:
  push:
    branches:
      - ci
env:
  PROJ_VERSION: 6.3.1
  PROJ_DATUM: 1.8
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Download
        run: |
          pwd
          curl https://download.osgeo.org/proj/proj-${PROJ_VERSION}.tar.gz | tar -xz
          curl -o datum.zip https://download.osgeo.org/proj/proj-datumgrid-${PROJ_DATUM}.zip
          unzip -o datum.zip -d proj-${PROJ_VERSION}/data
          rm -f datum.zip
      - name: Install requirements
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y --fix-missing --no-install-recommends \
                  software-properties-common build-essential ca-certificates \
                  make cmake wget unzip libtool automake \
                  zlib1g-dev libsqlite3-dev pkg-config sqlite3 libcurl4-gnutls-dev \
                  libtiff5-dev
      - name: build
        env:
          DESTDIR: /build
        run: |
          cd proj-${PROJ_VERSION} \
          && ./autogen.sh \
          && ./configure --prefix=/usr \
          && make -j$(nproc) \
          && make install
