name: CI
on:
  push:
    branches:
      - ci
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Cache libproj
        id: cache-libproj
        uses: actions/cache@v1
        with:
          path: $GITHUB_WORKSPACE/libproj
          key: ${{ runner.os }}-libproj-6_3_1 # 6.3.1 stands for libproj version
          restore-keys: |
            ${{ runner.os }}-libproj-

      - name: Fetch libproj
        if: steps.cache-libproj.outputs.cache-hit != 'true'
        uses: ./.github/actions/libproj

      - name: Install libproj
        run: |
          sudo mkdir -p /usr/lib/x86_64-linux-gnu/
          sudo cp $GITHUB_WORKSPACE/libproj/* /usr/lib/x86_64-linux-gnu/

      - name: setup env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}/go"
          echo "::add-path::${{ github.workspace }}/go/bin"

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.7

      - name: Cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: |
          make test
          make lint
          make typescript
