name: CI
on:
  push:
    branches:
      - ci
env:
  GO111MODULE: on
jobs:
  build_proj:
    name: Build proj from sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache libproj
        id: cache-libproj
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/libproj
          key: ${{ runner.os }}-libproj-6_3_1 # 6.3.1 stands for libproj version
          restore-keys: |
            ${{ runner.os }}-libproj-

      - name: Fetch libproj
        if: steps.cache-libproj.outputs.cache-hit != 'true'
        uses: ./.github/actions/libproj

      - name: Install libproj
        run: |
          sudo cp $GITHUB_WORKSPACE/libproj/* /usr/lib

      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "1.13.8"

      - name: Cache go modules
        uses: actions/cache@v1
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download go modules
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: make download

      - name: Test
        run: |
          ls -la
          echo $GOBIN
          printenv | grep GO
